// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkIjWp-8OtCt5NOlNrDLM5NanvB3dPJ2w',
    appId: '1:618990912300:web:3ab20f33e8390db112a289',
    messagingSenderId: '618990912300',
    projectId: 'flash-chat-c0af6',
    authDomain: 'flash-chat-c0af6.firebaseapp.com',
    storageBucket: 'flash-chat-c0af6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJsB1qXmL0T3LKZ8-ao04r9wA0QZB385k',
    appId: '1:618990912300:android:6e296bf59e524a7b12a289',
    messagingSenderId: '618990912300',
    projectId: 'flash-chat-c0af6',
    storageBucket: 'flash-chat-c0af6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0sswBRvOaYjJTpvwHN9LJy6tbRuLXHUY',
    appId: '1:618990912300:ios:b374bb263878fcad12a289',
    messagingSenderId: '618990912300',
    projectId: 'flash-chat-c0af6',
    storageBucket: 'flash-chat-c0af6.appspot.com',
    iosBundleId: 'com.example.flashMessengerApp',
  );
}
